### ISSUE TITLE
GitReminder-Concept

### ISSUE THREAD

**Issue by ADoebeling** [ADoebeling/GitReminder#1]
Build a GitReminder-Bot
- User `GitReminder` can be assigned to every Issue
- If you assign a Issue to GitReminder, it will (reopen and) assign the ticket back to the last assignee  the next day
- If you assign a Issue to GitReminder and post `@GitReminder +5`, the GitReminder will (reopen and) re-assign the ticket to last assignee in 5 days
- If you post `@GitReminder +5 @ADoebeling` it will (reopen and) and assign to @ADoebeling in 5 days
- if you post `@GitReminder 2015-07-07` it will (reopen and) and re-assign at specified date
- If you post `@GitReminder mailReminder ad@1601.com` it will send a mail-notification to specified address, CC to author of that post
- You can combine: `@GitReminder +5 @ADoebeling mailReminder ad@1601.com`
- if GitReminder doesn't understand your needs, it will answer "Sorry, I don't understand? Please check my Syntax

**Comment by ADoebeling** [comment]
User @GitReminder created.

**Comment by LBeckX** [comment]
@GitReminder +1 @ADoebeling

**Comment by ADoebeling** [comment]
I'm afraid this doesn't work yet ;-)

**Comment by LBeckX** [comment]
Da hst du recht ... hatte zuerst gedacht, dass es fertig ist :p

**Comment by ADoebeling** [comment]
![image](https://cloud.githubusercontent.com/assets/10674780/8505192/c7655d74-21df-11e5-88aa-a69b64db6eba.png)

2015-07-04 by @lb1601com / @adoebeling

**Comment by ADoebeling** [comment]
@lb1601com Pls. have a look: https://github.com/ADoebeling/GitReminder/commit/1fab46297f4bb40503ae06b0aad0f3937e9f15ac :-)

**Comment by LBeckX** [comment]
Ja sehr schön!

**Comment by ADoebeling** [comment]
@lb1601com Please go on and implement the missing functions :-)

**Comment by LBeckX** [comment]
lass das lieber zusammen machen in Nerdnight #15

**Comment by LBeckX** [comment]
Erster Stand fertig.
