### ISSUE TITLE
MySQL-Aufrufe in SPs implementieren

### ISSUE THREAD

**Issue by ADoebeling** [ADoebeling/GitReminder#12]
s. https://github.com/ADoebeling/GitReminder/commit/2b34ae74729826a449f8dc52c7bdcf7fdd3d061d#commitcomment-12739128

**Comment by LBeckX** [comment]
Soll ich das jetzt noch machen?
Habe jetzt ja mit meiner MySQL-Übung auch SPs gemacht.
