### ISSUE TITLE
Code-Review 15-08-17

### ISSUE THREAD

**Issue by ADoebeling** [ADoebeling/GitReminder#13]
https://github.com/ADoebeling/GitReminder/commit/2b34ae74729826a449f8dc52c7bdcf7fdd3d061d

**Comment by LBeckX** [comment]
Ok bin durch. Habe jetzt ja noch einiges dazugeschrieben und bitte desswegen um erneutes Review :+1:

**Comment by ADoebeling** [comment]
In der letzten Version gab es ja noch den bug, dass tickets beliebig oft vom reminder bearbeitet wurden. BItte Info, wenn ich wieder draufschauen soll

**Comment by lb1601com** [comment]
Problem gefixt. Bitte den gesammten Code anschauen
