### ISSUE TITLE
https://github.com/tan-tan-kanarek/github-php-client/blob/master/client/services/GitHubIssues.php

### ISSUE THREAD

**Issue by LBeckX** [ADoebeling/GitReminder#14]
https://github.com/tan-tan-kanarek/github-php-client/blob/master/client/services/GitHubIssues.php

aditAnIssue() braucht den Titel des Issues ... Bemerkung machen: "Dieser sollte optional sein."

**Comment by ADoebeling** [comment]
WAtn damit? Kann das nciht weg? In Anbetracht der Anzahl der Probleme, die wir mit dem Framework haben, lohnt es sich glaube nicht die Bugs einzeln zu filen
