### ISSUE TITLE
Mailnotification

### ISSUE THREAD

**Issue by LBeckX** [ADoebeling/GitReminder#25]
Soll Link enthalten und auch Footer der Agentur. ~~Evtl.~~ auch die letzten 5 Kommentare.

**Comment by LBeckX** [comment]
Möglichkeit ist gegeben, aber Umsetzung bzw. das durchdachte System weißt noch Fehler auf

**Comment by ADoebeling** [comment]
Büdde nüscht vergessen

**Comment by LBeckX** [comment]
Ist beendet
