### ISSUE TITLE
GitReminder - Fehler vom 15.08.

### ISSUE THREAD

**Issue by LBeckX** [ADoebeling/GitReminder#65]
Fehler ist m.E. nicht reproduzierbar:

```
[Sat, 13 Aug 2016 03:39:07 +0200] [error] exceptionHandler();
// This system is locked. Pls. contact admin! in 
/kunden/226796_91058/kunden/gitreminder.1601.com/www/class/gitreminder.class.php:83 | 
#0 /kunden/226796_91058/kunden/gitreminder.1601.com/www/class/gitreminder.class.php(63): gitReminder->lockFile()
#1 /kunden/226796_91058/kunden/gitreminder.1601.com/www/script/gitreminder.php(4): gitReminder->__construct()
#2 /kunden/226796_91058/kunden/gitreminder.1601.com/www/script/gitreminder_new.sh(10): require_once('/kunden/226796_...')
#3 {main}
```

**Comment by ADoebeling** [comment]
- Bitte Code immer als code formatieren.
- Wenn das alles ist, was im Log steht, ist dein Log kacke.

**Comment by LBeckX** [comment]
Bzw. dein Log :D

**Comment by ADoebeling** [comment]
https://github.com/ADoebeling/GitReminder/blob/master/class/log.class.php
ich glaube "mein" Log kann nix dafür, wenn Du ihm keine Beschreibung mitgibst.

https://github.com/ADoebeling/GitReminder/blob/master/bootstrap.php#L18
`@trigger_error('',E_USER_ERROR);`
Warum gibst Du hier keine Desc mit?

und wo ist überhaupt das Log-File?
/kunden/226796_91058/kunden/gitreminder.1601.com/www/logs
Hier ist kein Fehler erkennbar. Ich hoffe Du hast den CronJob nicht wieder doppelt ausgeführt?

**Comment by LBeckX** [comment]
Der Fehler passierte am 13. -  Das war ein Samstag. Ich habe an diesem Tag da nichts gemacht.

/kunden/226796_91058/kunden/gitreminder.1601.com/www/logs/syslog_160813_1SRV.log*

Das war der Tag, wo der Fehler passierte.

**Comment by LBeckX** [comment]
https://github.com/ADoebeling/GitReminder/blob/master/bootstrap.php#L18
Das hast du eingebaut, bei mir ^^

**Comment by ADoebeling** [comment]
wieso läuft der Cron weiter, wenn ein Fehler auftritt?!

**Comment by LBeckX** [comment]
Das war meine Frage an dich. Ich hätte gedacht, dass du evtl. das .lock-File gelöscht hast, oder die bootstrap.php schreibt eine Mail auch bei keinem Fehler?!

**Comment by LBeckX** [comment]
1. Unlink return abfragen
2. schauen ob das "lock-file" noch existiert und dokumentieren im Fehlerfall
3. Uhrzeit festlegen 0 - 6 nicht ausführen

**Comment by LBeckX** [comment]
Sachen eingebaut und GitReminder aktualisiert.
