### ISSUE TITLE
[GitReminder] Aktuelle Fixes!

### ISSUE THREAD

**Issue by LBeckX** [ADoebeling/GitReminder#72]
- [ ] Unerklärliches assignen von Tickets: https://github.com/ADoebeling/GitReminder/issues/71
- [ ] GitReminder soll Tickets wieder öffen: https://github.com/ADoebeling/GitReminder/issues/70
- [ ] Exception handling: https://github.com/ADoebeling/GitReminder/issues/69
- [ ] Gitignore: https://github.com/ADoebeling/GitReminder/issues/59
- [ ] Aufteilung d. Config: https://github.com/ADoebeling/GitReminder/issues/32
- [ ] Mailnotification: https://github.com/ADoebeling/GitReminder/issues/25

**Comment by ADoebeling** [comment]
Von: admin-bounces@1601.com [mailto:admin-bounces@1601.com] Im Auftrag von RE User
Gesendet: Dienstag, 11. Oktober 2016 11:59
An: admin@1601.com
Betreff: [Admin] [GitReminder] System got locked

This system is locked. Pls. contact admin! in /kunden/226796_91058/kunden/gitreminder.1601.com/www/class/gitreminder.class.php:83

exceptionHandlerArray

Wie kam es dazu wieder? Problem hat sich auch von selbst gelöst?

**Comment by LBeckX** [comment]
Ist beendet
