### ISSUE TITLE
GitReminder Kommentare laden

### ISSUE THREAD

**Issue by LBeckX** [ADoebeling/GitReminder#9]

**Comment by ADoebeling** [comment]
https://github.com/ADoebeling/GitReminder/commit/2b34ae74729826a449f8dc52c7bdcf7fdd3d061d#diff-40cf71a4be50401471cbc8d065f948f3R84
- loadStoredTasksFromDatabase() ist noch nicht implementiert
- Parameter-Liste fehlerhaft
- Bitte bei noch nicht implementierten Methoden eine eine Exeption werfen, vgl. https://github.com/ADoebeling/GithubIssueImporter/blob/master/class/githubIssueImporter.class.php#L61
- Bitte eigene methode setMysql()

**Comment by LBeckX** [comment]
Ich dachte wir brauchen eine Methode, die das für uns macht also auswählt wo wir speichern wollen bzw. der wir sagen, wo wir speichern wollen.

**Comment by ADoebeling** [comment]
korrekt. `loadStoredTasks()` lädt über eine der `loadStoredTasksXXX()`-Methoden die Daten rein.
Dafür muss die `loadStoredTasksDatabase()` aber natürlich selbst erstmal vollständig implementiert sein. Die Master-Methode greift selbst ja nur auf diese Methode zurück

**Comment by LBeckX** [comment]
Fertig.
